### ISSUE TITLE
[Suggestion] Add Open Graph Meta Tags

### ISSUE THREAD

**Issue by Ruriko** [ShugetsuSoft/pixivel-front#1]
Adding og tags is handy to have cause visitors sometime share links on social media platforms

**Comment by Rorical** [comment]
That's definitely a good idea! Thanks for your suggestion. What social media platforms should we allow users to share our links to?

**Comment by Ruriko** [comment]
facebook, twitter, instagram, pinterest, tumblr
I think just having the basic og tags should work with any social media plaforms
```
<meta property="og:title" content="Place title here">
<meta property="og:description" content="Place description here">
<meta property="og:image" content="Place image url here">
```

**Comment by Rorical** [comment]
Actually, I'm planning to add some buttons that allow users to share the link. And because this website is designed for Chinese users (pixiv.net is blocked by GFW), I would first consider adding some social media such as WeChat, Weibo, etc. Other platforms are ok.

**Comment by Ruriko** [comment]
Even if you add buttons you'll still need to add og tags cause many social media platforms can't execute javascript so when you try sharing on wechat you won't see a thumbnail of the image

**Comment by Rorical** [comment]
Oh I got your point. Maybe og tag needs support from the backend? 
I will consider implementing one.

**Comment by EL-File4138** [comment]
Feature Request Registered, now close #1.
