### ISSUE TITLE
CORS header?

### ISSUE THREAD

**Issue by Ruriko** [ShugetsuSoft/pixivel-front#5]
Does your app add any CORS headers? cause I'm getting this error
`Access to XMLHttpRequest at 'https://api.adoreanime.com/api/pixiv/rank/?mode=day&date=2022-01-29&page=1' from origin 'https://beta.adoreanime.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I'm using my own api and have enabled cors in nginx.

**Comment by Rorical** [comment]
Backend App should add CORS headers, but it's for pixivel. You should modify them in modules/responser/responser.go
